
export const academicItems = [
    {title:"Licenciatura em Tecnologias de Informação",
    startDate: "Setembro 2018",
    endDate: "Julho 2021",
    description:"Faculdade de Ciências da Universidade de Lisboa",
    curricularPlan: [
        {title:"Controvérsias Científicas"},
        {title:"Informática na Ótica do Utilizador"},
        {title:"Arquiteturas de Computadores"},
        {title:"Elementos de Matemática I"},
        {title:"Produção de Documentos Técnicos"},
        {title:"Programação I"},
        {title:"Elementos de Matemática II"},
        {title:"Introdução às Probabilidades e Estatística"},
        {title:"Introdução às Tecnologias Web"},
        {title:"Programação II"},
        {title:"Redes de Computadores"},
        {title:"Bases de Dados"},
        {title:"Fundamentos e Técnicas de Visualização"},
        {title:"Interação com Computadores"},
        {title:"Programação Centrada em Objetos"},
        {title:"Sistemas Operativos"},
        {title:"Análise e Desenho de Software"},
        {title:"Aplicações Distribuídas"},
        {title:"Aplicações e Serviços na Web"},
        {title:"Conceção de Produto"},
        {title:"Sistemas Inteligentes"},
        {title:"Planeamento e Gestão de Projeto"},
        {title:"Construção de Sistemas de Software"},
        {title:"Projeto de Tecnologias de Redes"},
        {title:"Projeto de Tecnologias de Informação"},
        

    ]},
    {title:"Minor em Design e Multimédia",
    startDate: "Setembro 2020",
    endDate: "Julho 2021",
    description: "Faculdade de Belas Artes da Universidade de Lisboa",
    curricularPlan: [
        {title:"Teoria da Imagem I"},
        {title:"Cultura Visual"},
        {title:"Programação Gráfica"},
        {title:"Metodologia Projetual Multimédia"},
        {title:"Sistemas Interativos"},
    ]},
    {title:"Mestrado em Informática",
    startDate: "Setembro 2021",
    endDate: "Setembro 2023",
    description: "Faculdade de Ciências da Universidade de Lisboa",
    curricularPlan: [
        {title:"Aprendizagem Automática"},
        {title:"Análise e Gestão de Risco em Segurança Informática"},
        {title:"Bases de Dados Avançadas"},
        {title:"Computação Móvel"},
        {title:"Experiência de Utilização"},
        {title:"Desenho e Análise de Algoritmos"},
        {title:"Aplicações na Web"},
        {title:"Computação em Nuvem"},
        {title:"Internet das Coisas"},
        {title:"Prospeção de Dados"},
    ]}
]